services:
  xampp:
    image: tomsik68/xampp
    ports:
      - "44162:22"
      - "41063:80"
      - "41064:3306"
    volumes:
      # Sitios web
      - ./xampp/ajpdsoft:/www/ajpdsoft
 
      # Configuración apache
      - ./xampp/my_apache_conf/:/opt/lampp/apache2/conf.d
      
      # Persistencia MySQL
      - ./xampp/mysql/ajpdsoft:/opt/lampp/var/mysql/ajpdsoft
    restart: always