services:
  php:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: servidor-php
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
volumes:
  html: {}